FROM rust:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        clang \
        cmake \
        git \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        xz-utils \
        zstd \
    && ln -sf /usr/local/cargo/bin/* /usr/local/bin/ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
