//! Generated by build.rs at compile time. The actual contents
//! (EmbeddedBinary struct + EMBEDDED constant) live in
//! $OUT_DIR/embedded.rs and are included verbatim here.
include!(concat!(env!("OUT_DIR"), "/embedded.rs"));
